import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { LegalPage, type LegalSection } from "@/components/legal/legal-page";
import { isValidLocale } from "@/lib/i18n/locale";

export const metadata: Metadata = { title: "Privacy Policy | OnlineDoc", description: "Learn how OnlineDoc collects, uses, safeguards, and manages personal information.", robots: { index: true, follow: true } };

const sections: LegalSection[] = [
  { title: "1. Introduction", paragraphs: ["OnlineDoc provides digital healthcare services, including online consultations and digital health education. This Privacy Policy explains how personal information is handled when you use our website and services.", "OnlineDoc is the platform name used throughout this policy. Where applicable law requires the operator's registered name or particulars, those details should be supplied through the site's legal-operator configuration; this policy does not invent a legal entity."] },
  { title: "2. Who We Are", paragraphs: ["OnlineDoc processes personal information in connection with account creation, consultations, communications, payments, digital products, and the operation and security of the platform. For privacy requests, use the Contact page linked below."] },
  { title: "3. Information We Collect", paragraphs: ["Depending on how you use OnlineDoc, information may include:"] , bullets: ["Account information: name, email address, phone number where collected, account credentials, and email verification information.", "Profile information: date of birth, gender where collected, and contact information.", "Healthcare information: symptoms, medical history, consultation information, clinical information you choose to provide, consultation messages, uploaded images and files, consultation notes, and treatment-related information where applicable.", "Clinician information: name, qualifications, registration number, specialization, biography, experience, and availability.", "Transaction information: orders, consultation and digital product purchases, payment status, transaction references, and refund information.", "Technical information: IP address, browser and device information, authentication and session information, security and audit information, and usage information."] },
  { title: "4. How We Collect Information", paragraphs: ["We collect information when you register or manage an account, request or take part in a consultation, exchange chat messages, upload files or images, make a purchase, submit a contact form, use the website, or interact with technical systems that support authentication, security, and platform operation."] },
  { title: "5. How We Use Personal Data", paragraphs: ["We use personal information to provide consultations; connect patients with clinicians; manage accounts and consultation history; process payments and deliver digital products; respond to support requests; send service and account notifications; maintain platform security; prevent fraud and abuse; improve platform functionality; and meet legal, regulatory, healthcare, and record-keeping obligations. Health information is not used for advertising."] },
  { title: "6. Health Information", paragraphs: ["Health information is sensitive personal information. OnlineDoc applies appropriate confidentiality and security measures to protect it. Access is limited to legitimate healthcare, operational, legal, security, or other purposes permitted by law and appropriate role-based access.", "We disclose healthcare information only where permitted or required by law and, where applicable, with appropriate authorization or consent. Clinicians involved in your care may need relevant information to assess and provide a consultation."] },
  { title: "7. Legal Bases for Processing", paragraphs: ["The legal basis depends on the activity and applicable law. It may include your consent; processing needed to provide a service or perform a contract; compliance with a legal obligation; legitimate interests where permitted, such as protecting and operating the platform; or public interest and another lawful basis where applicable. We do not rely on one basis for every activity. Where processing relies on consent, you may withdraw it, subject to legal limits and the effect this may have on a service."] },
  { title: "8. Sharing Personal Data", paragraphs: ["Information may be shared with the clinician assigned to your consultation; service providers and processors supporting OnlineDoc; payment providers; hosting and infrastructure providers; email and notification providers; and storage providers. We may also disclose information to regulators, courts, law enforcement, or other authorities where legally required or permitted.", "We do not sell personal health information. Service providers may process information only as needed to provide their services and under appropriate safeguards."] },
  { title: "9. International Data Transfers", paragraphs: ["Some service providers or infrastructure may process information outside Kenya. Where an international transfer applies, OnlineDoc will use appropriate safeguards as required by applicable Kenyan data protection law."] },
  { title: "10. Data Security", paragraphs: ["OnlineDoc uses reasonable technical and organizational safeguards appropriate to the information and risks. These include access controls, authentication and authorization, secure transmission, restricted access, and security logging or monitoring where implemented. Encryption is used where implemented for the relevant system or transfer. We review security practices as appropriate; no online service can guarantee absolute security."] },
  { title: "11. Data Retention", paragraphs: ["Personal information is retained only for as long as reasonably necessary for the purposes for which it was collected, applicable legal obligations, healthcare records, dispute resolution, security, and legitimate operational requirements. Retention can differ by record type and legal requirements; we do not state a fixed period here."] },
  { title: "12. Your Data Subject Rights", paragraphs: ["Subject to applicable law, you may have the right to be informed, access your information, request rectification, request erasure where applicable, object to processing, request restriction where applicable, request data portability where applicable, and withdraw consent where processing relies on consent. These rights may be limited by legal duties, healthcare record retention requirements, the rights of others, or other lawful grounds."] },
  { title: "13. How to Exercise Your Rights", paragraphs: ["CONTACT_PAGE_LINK", "Please describe the right you wish to exercise and the relevant account or consultation. Include your account email or another identifier and enough context to locate the information. Do not send passwords or unnecessary medical details. We may ask for reasonable information to verify your identity before acting, and we will respond in accordance with applicable law."] },
  { title: "14. Children's Data", paragraphs: ["OnlineDoc should not knowingly collect children's personal data without appropriate authorization and safeguards where required. Healthcare services may involve minors. Where a minor's information is processed, applicable consent, authorization, confidentiality, and health-data requirements apply."] },
  { title: "15. Cookies and Similar Technologies", paragraphs: ["OnlineDoc uses essential session and similar technologies needed for functions such as authentication, maintaining a signed-in session, and platform operation. The website also uses platform analytics functionality. We do not claim the use of any additional third-party advertising or tracking technologies here. Browser settings may allow you to manage cookies, but disabling essential technologies can affect service functionality."] },
  { title: "16. Payments", paragraphs: ["Payment information may be processed by the payment provider used for a transaction. OnlineDoc receives transaction-related information such as payment status and references needed to manage orders and consultations. OnlineDoc does not claim to store full card details."] },
  { title: "17. Third-Party Links", paragraphs: ["The website may link to external websites or services. Those services have their own privacy practices, which OnlineDoc does not control. Review their privacy information before providing information to them."] },
  { title: "18. Data Breaches and Security Incidents", paragraphs: ["OnlineDoc maintains procedures to detect, assess, respond to, and report personal-data breaches where required by applicable law. Any required notifications will be made in accordance with the applicable legal requirements."] },
  { title: "19. Changes to This Privacy Policy", paragraphs: ["We may update this policy as the platform or legal requirements change. Updates will be published on this page and the effective and last updated dates will be revised. Please review this page periodically."] },
  { title: "20. Contact", paragraphs: ["For questions about this policy or to make a privacy request, use our Contact page. OnlineDoc does not publish a separate privacy email address here.", "CONTACT_PAGE_LINK"] },
];

export default function PrivacyPolicyPage({ params }: { params: { locale: string } }) {
  if (!isValidLocale(params.locale)) notFound();
  return <LegalPage title="Privacy Policy" sections={sections} locale={params.locale} />;
}
