import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { LegalPage, type LegalSection } from "@/components/legal/legal-page";
import { isValidLocale } from "@/lib/i18n/locale";

export const metadata: Metadata = { title: "Terms of Service | OnlineDoc", description: "Terms governing use of OnlineDoc consultations, digital products, and platform services.", robots: { index: true, follow: true } };

const sections: LegalSection[] = [
  { title: "1. Introduction", paragraphs: ["These Terms of Service (Terms) govern your access to and use of OnlineDoc, including online consultations, chat consultations, health education, and downloadable digital products. OnlineDoc is the platform through which patients can access licensed clinicians and related services."] },
  { title: "2. Acceptance of Terms", paragraphs: ["By accessing or using OnlineDoc, creating an account, placing an order, or booking a consultation, you agree to these Terms and our Privacy Policy. If you do not agree, do not use the relevant service. Additional terms presented for a particular service or purchase also apply."] },
  { title: "3. Eligibility", paragraphs: ["You must be able to enter into a binding agreement or use OnlineDoc with the involvement and authorization of a parent, guardian, or other person where required by law. Healthcare services may involve minors; applicable consent, authorization, confidentiality, and health-data requirements apply. You must provide accurate information and use the service only where it is lawfully available to you."] },
  { title: "4. OnlineDoc Services", paragraphs: ["OnlineDoc provides digital tools for account management, consultations, patient-clinician communication, healthcare education, and purchases of digital products. OnlineDoc provides the platform; a consultation is a healthcare interaction between a patient and the clinician providing it. OnlineDoc is not itself identified by these Terms as the individual healthcare provider. The clinician is responsible for professional clinical care within their role and applicable standards."] },
  { title: "5. Accounts and Account Security", paragraphs: ["Some services require an account. Keep your credentials confidential, use accurate account details, and promptly notify OnlineDoc through the Contact page if you believe your account has been accessed without authorization. You are responsible for activity through your account to the extent permitted by law."] },
  { title: "6. Patient Responsibilities", paragraphs: ["You agree to provide accurate and complete information relevant to your care, update it when it changes, communicate respectfully, follow reasonable instructions for using the platform, and use the service only for lawful purposes. Do not use online consultation as a substitute for emergency care."] },
  { title: "7. Clinician Responsibilities", paragraphs: ["Clinicians using OnlineDoc must provide accurate professional information, maintain required licenses and registrations, act within their qualifications and scope of practice, protect patient confidentiality, and comply with applicable professional and legal duties. Clinical decisions remain with the licensed healthcare professional providing the consultation."] },
  { title: "8. Consultations", paragraphs: ["A consultation connects a patient with a clinician for a healthcare interaction. Availability, scope, and suitability depend on the clinician and information provided. A clinician may determine that an online consultation is not appropriate and recommend another form of care. A booking or payment does not guarantee a particular diagnosis, treatment, prescription, or result."] },
  { title: "9. Chat Consultations", paragraphs: ["Chat consultations take place through the communication features made available for the consultation. Messages and files should relate to the consultation and must not be used to obtain emergency assistance. Response timing may vary based on clinician availability and the nature of the service; do not assume a message has been reviewed until the clinician responds."] },
  { title: "10. Follow-up Consultations", paragraphs: ["A follow-up is available only where offered or agreed for the relevant consultation. Any scope, timing, or charges applicable to a follow-up will be shown or communicated for that service. Do not assume a follow-up is included unless it is expressly stated."] },
  { title: "11. Urgent Consultations", paragraphs: ["Urgent consultations are intended for urgent but non-emergency concerns. They are not an emergency response service and may not be suitable for every condition. If your symptoms could be life-threatening or need immediate attention, seek emergency care now."] },
  { title: "12. Emergency and Life-Threatening Situations", paragraphs: ["OnlineDoc does not replace emergency medical care. If you may be experiencing a medical emergency or a life-threatening condition, do not wait for an online response: seek immediate emergency care or contact the appropriate emergency services in your location. OnlineDoc does not publish a specific emergency telephone number in these Terms."] },
  { title: "13. Medical Information and Health Education", paragraphs: ["Website material, articles, and health education are for general educational purposes. Health information on the website should not be treated as a diagnosis without an appropriate clinical assessment. Information provided as part of a consultation is subject to the clinician's professional assessment and duties."] },
  { title: "14. Digital Products", paragraphs: ["OnlineDoc offers downloadable healthcare resources such as meal plans, nutrition guides, and patient education booklets. Digital products provide educational information and do not automatically create a clinician-patient relationship. A product is not necessarily individually tailored to its purchaser. Consider your circumstances and seek professional advice where appropriate."] },
  { title: "15. Orders and Payments", paragraphs: ["OnlineDoc supports payment for consultations and digital products through the payment methods presented at checkout. Payment processing may be handled by the payment provider used for the transaction. Orders, access, or consultation services may depend on payment confirmation. Do not provide payment credentials through chat or contact forms."] },
  { title: "16. Pricing", paragraphs: ["Prices and applicable charges are displayed or communicated before you complete a purchase. The price shown for your order at checkout applies, subject to correction of an obvious error and applicable law. Any change to prices applies prospectively and does not change a completed purchase unless required by law."] },
  { title: "17. Refunds and Cancellations", paragraphs: ["The applicable refund and cancellation rules will be displayed at checkout or provided in the relevant service terms. OnlineDoc's business policy for refund periods and consultation cancellations must be finalized and configured for the relevant offer; these Terms do not promise a specific refund period. Nothing in this section limits rights that cannot be excluded under applicable law. Contact OnlineDoc through the Contact page for an order-specific request."] },
  { title: "18. Intellectual Property", paragraphs: ["OnlineDoc and its licensors retain rights in the platform, branding, software, and content except for rights belonging to others. Subject to these Terms and any purchase conditions, you may use purchased digital products for your personal, non-commercial purposes. You may not reproduce, distribute, sell, or publicly share protected content without permission or a legal right to do so."] },
  { title: "19. User Content", paragraphs: ["You retain rights you hold in information and content you submit. You authorize OnlineDoc to host, process, and display that content as needed to operate the platform, provide your requested services, maintain security, and meet legal obligations. You must have the right to submit content and must not upload unlawful, infringing, malicious, or irrelevant material. Healthcare information is handled under the Privacy Policy and applicable law."] },
  { title: "20. Prohibited Conduct", paragraphs: ["You must not misuse the service, interfere with its security or operation, attempt unauthorized access, impersonate another person, submit knowingly false information, harass users or clinicians, upload malicious code, infringe rights, or use the platform for unlawful activity."] },
  { title: "21. Platform Availability", paragraphs: ["OnlineDoc may change, maintain, suspend, or discontinue features as needed for operation, security, or legal compliance. We aim to keep the platform available but do not guarantee uninterrupted or error-free access. We will handle these actions consistently with applicable law and any rights that cannot be excluded."] },
  { title: "22. Third-Party Services", paragraphs: ["The platform may rely on or link to services operated by third parties, including payment and infrastructure services. Their terms and privacy practices may apply to your use of them. OnlineDoc is not responsible for third-party services to the extent permitted by law."] },
  { title: "23. Privacy", paragraphs: ["Our Privacy Policy explains how personal information, including sensitive healthcare information, is handled. By using OnlineDoc, you acknowledge that information will be processed as described there and under applicable data protection law."] },
  { title: "24. Medical Disclaimer", id: "medical-disclaimer", paragraphs: ["OnlineDoc does not replace emergency medical care. Online health information is educational unless provided as part of a consultation. Website health information should not be treated as a diagnosis without an appropriate clinical assessment. Clinical decisions remain the responsibility of the licensed healthcare professional providing the consultation. You should provide accurate and complete information during consultations. No online consultation guarantees a particular diagnosis, treatment outcome, or health result. Nothing in these Terms excludes professional duties or rights that cannot lawfully be excluded."] },
  { title: "25. Limitation of Liability", paragraphs: ["To the extent permitted by applicable law, OnlineDoc is not liable for indirect or consequential loss arising from use of the platform. Nothing in these Terms excludes or limits liability, professional duties, consumer rights, or remedies that cannot be excluded or limited by law. These Terms do not make OnlineDoc the clinician providing an individual consultation."] },
  { title: "26. Indemnification", paragraphs: ["To the extent permitted by law, you are responsible for losses or claims arising from your unlawful use of the platform, your material breach of these Terms, or content you submit that infringes another person's rights. This does not apply to the extent a claim results from OnlineDoc's own breach of law or non-excludable duty."] },
  { title: "27. Suspension and Termination", paragraphs: ["You may stop using OnlineDoc at any time. OnlineDoc may restrict, suspend, or terminate access where reasonably necessary for security, suspected abuse, legal compliance, or a material breach of these Terms. Where appropriate and lawful, we will provide notice and an opportunity to address the issue. Termination does not remove rights or obligations that accrued earlier or records that must be retained by law."] },
  { title: "28. Changes to the Service", paragraphs: ["We may update or change the service to improve it, respond to legal or security needs, or reflect operational changes. Where a change materially affects an active paid service, we will handle it in accordance with applicable law and the terms presented for that purchase."] },
  { title: "29. Changes to These Terms", paragraphs: ["We may revise these Terms from time to time. The revised version will be published on this page with an updated effective and last updated date. Continued use after the revised Terms take effect means you accept them to the extent permitted by law. If you do not agree, stop using the affected services."] },
  { title: "30. Governing Law", paragraphs: ["These Terms are governed by the laws of Kenya, subject to any mandatory legal protections that apply to you. This does not specify an exclusive court, arbitration institution, or dispute forum."] },
  { title: "31. Dispute Resolution", paragraphs: ["If you have a concern, contact OnlineDoc first so we can try to understand and address it. Nothing in these Terms prevents you from using a complaint process or legal remedy available under applicable law. Any dispute procedure required by law will apply."] },
  { title: "32. Contact Information", paragraphs: ["For questions about these Terms, an order, or the service, use the OnlineDoc Contact page. No separate address, telephone number, or email is stated in these Terms.", "CONTACT_PAGE_LINK"] },
];

export default function TermsOfServicePage({ params }: { params: { locale: string } }) {
  if (!isValidLocale(params.locale)) notFound();
  return <LegalPage title="Terms of Service" sections={sections} locale={params.locale} />;
}
